name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2
  
  commit-firmware:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'  # Only commit on push/workflow_dispatch, not PRs
    steps:
    - uses: actions/checkout@v4
    
    # Download the firmware artifact created by the build job from this specific workflow run
    - name: Download firmware artifact
      uses: actions/download-artifact@v4
      with:
        name: firmware
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        run-id: ${{ github.run_id }}
    
    # Debug: List what was downloaded
    - name: List downloaded files and show checksums
      run: |
        echo "=== Files in current directory ==="
        ls -la
        echo "=== Checksums of downloaded files ==="
        sha256sum corne_*.uf2 2>/dev/null || echo "No .uf2 files found in current directory"
        echo "=== Existing firmware-builds checksums ==="
        sha256sum firmware-builds/corne_*.uf2 2>/dev/null || echo "No existing firmware files"
    
    # Create firmware-builds directory if it doesn't exist
    - name: Create firmware-builds directory
      run: mkdir -p firmware-builds
    
    # Show file differences before moving
    - name: Compare files before moving
      run: |
        echo "=== File size comparison ==="
        ls -l corne_*.uf2 2>/dev/null || echo "No downloaded .uf2 files"
        ls -l firmware-builds/corne_*.uf2 2>/dev/null || echo "No existing firmware files"
        echo "=== Binary diff check ==="
        if [ -f "corne_left-nice_nano_v2-zmk.uf2" ] && [ -f "firmware-builds/corne_left-nice_nano_v2-zmk.uf2" ]; then
          if cmp -s "corne_left-nice_nano_v2-zmk.uf2" "firmware-builds/corne_left-nice_nano_v2-zmk.uf2"; then
            echo "LEFT: Files are identical"
          else
            echo "LEFT: Files are different"
          fi
        fi
        if [ -f "corne_right-nice_nano_v2-zmk.uf2" ] && [ -f "firmware-builds/corne_right-nice_nano_v2-zmk.uf2" ]; then
          if cmp -s "corne_right-nice_nano_v2-zmk.uf2" "firmware-builds/corne_right-nice_nano_v2-zmk.uf2"; then
            echo "RIGHT: Files are identical"
          else
            echo "RIGHT: Files are different"
          fi
        fi
    
    # Move firmware files to firmware-builds folder
    - name: Move firmware files
      run: |
        mv corne_left-nice_nano_v2-zmk.uf2 firmware-builds/
        mv corne_right-nice_nano_v2-zmk.uf2 firmware-builds/
    
    # Force git to see both files as changed
    - name: Force update timestamps and add files
      run: |
        touch firmware-builds/corne_left-nice_nano_v2-zmk.uf2
        touch firmware-builds/corne_right-nice_nano_v2-zmk.uf2
        git add firmware-builds/corne_left-nice_nano_v2-zmk.uf2
        git add firmware-builds/corne_right-nice_nano_v2-zmk.uf2
        echo "=== Git status after adding ==="
        git status --porcelain firmware-builds/
    
    # Commit the firmware files
    - name: Commit firmware files
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: 'Auto-update firmware builds'
        file_pattern: 'firmware-builds/corne_left-nice_nano_v2-zmk.uf2 firmware-builds/corne_right-nice_nano_v2-zmk.uf2'
