name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2
  
  commit-firmware:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware-builds/
          
      # Commit the firmware files
      - name: Commit firmware files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto-update firmware builds'
          file_pattern: 'firmware-builds/*.uf2'
