name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2
  
  commit-firmware:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: firmware
          
      - name: Move firmware files
        run: |
          mkdir -p firmware-builds
          echo "=== Available firmware files ==="
          find firmware -name "*.uf2" -ls
          echo "=== Copying firmware files ==="
          find firmware -name "*.uf2" -exec cp -v {} firmware-builds/ \;
          echo "=== Final firmware-builds directory ==="
          ls -la firmware-builds/
          
      - name: Commit firmware
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "=== Git status before staging ==="
          git status
          echo "=== Adding firmware-builds/ ==="
          git add firmware-builds/
          echo "=== Git status after staging ==="
          git status
          echo "=== Staged changes ==="
          git diff --staged --stat
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update firmware builds [skip ci]"
            git push
          fi
