name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2
  
  commit-firmware:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: firmware
          
      - name: Move firmware files
        run: |
          mkdir -p firmware-builds
          find firmware -name "*.uf2" -exec cp {} firmware-builds/ \;
          
      - name: Commit firmware
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add firmware-builds/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update firmware builds [skip ci]"
            git push
          fi
